//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PortalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PortalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resource.PortalResource", typeof(PortalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ForgotPasswordViewModel_Email_label {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel_Email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address required.
        /// </summary>
        public static string ForgotPasswordViewModel_Email_Required {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code completion required.
        /// </summary>
        public static string RegisterViewModel_Captcha_required {
            get {
                return ResourceManager.GetString("RegisterViewModel_Captcha_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string RegisterViewModel_City_label {
            get {
                return ResourceManager.GetString("RegisterViewModel_City_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City is field required.
        /// </summary>
        public static string RegisterViewModel_City_required {
            get {
                return ResourceManager.GetString("RegisterViewModel_City_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string RegisterViewModel_Country_label {
            get {
                return ResourceManager.GetString("RegisterViewModel_Country_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string RegisterViewModel_FirstName_label {
            get {
                return ResourceManager.GetString("RegisterViewModel_FirstName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name is required.
        /// </summary>
        public static string RegisterViewModel_FirstName_required {
            get {
                return ResourceManager.GetString("RegisterViewModel_FirstName_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string RegisterViewModel_Number_label {
            get {
                return ResourceManager.GetString("RegisterViewModel_Number_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalCode.
        /// </summary>
        public static string RegisterViewModel_PostalCode_label {
            get {
                return ResourceManager.GetString("RegisterViewModel_PostalCode_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string RegisterViewModel_State_label {
            get {
                return ResourceManager.GetString("RegisterViewModel_State_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string RegisterViewModel_Street_label {
            get {
                return ResourceManager.GetString("RegisterViewModel_Street_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurName.
        /// </summary>
        public static string RegisterViewModel_SurName_label {
            get {
                return ResourceManager.GetString("RegisterViewModel_SurName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SurName is required.
        /// </summary>
        public static string RegisterViewModel_SurName_required {
            get {
                return ResourceManager.GetString("RegisterViewModel_SurName_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string RegisterViewModel_Title_label {
            get {
                return ResourceManager.GetString("RegisterViewModel_Title_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title field is required.
        /// </summary>
        public static string RegisterViewModel_Title_required {
            get {
                return ResourceManager.GetString("RegisterViewModel_Title_required", resourceCulture);
            }
        }
    }
}
